version: "3.8"

services:
  db:
    image: postgres:16
    container_name: config_manager_database
    env_file:
      - ./src/api/.env

    ports:
      - "5432:5432"
    networks:
      - config-manager-network

networks:
  config-manager-network:
    driver: bridge
